language: node_js
node_js: 14.16.1

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "tico-gux"
    token:
      secure: "75e7f77ec2a40db19a75b10874526b793db409c6"
notifications:
  slack: builds-espacio:FYgdWLifWHXck8FnYmgIWoWQ
deploy:
  provider: heroku
  api_key:
    secure: "dc0612de-9e19-4c8b-9b49-13950c34c954"
  app: sw-cicd
  on:
    branch: main
